### ISSUE TITLE
Span tag appearing in the browser tab name

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsb/reveal-presentations#1]
Once a slide is published in the tab in the browser, a `<span>` tag is appearing in the display: 

<img width="623" alt="2021-09-01_10-58-34" src="https://user-images.githubusercontent.com/480667/131695818-683210fe-d63c-4c92-a310-5eb6e5153034.png">

**Comment by r-a-y** [comment]
This occurred because I'm using `the_archive_title()`, which is meant to be used for headings like `<h1>`. Instead, I'm using it for the page title.

Should be fixed now.

**Comment by mrjarbenne** [comment]
It is fixed now! Thanks!
