### ISSUE TITLE
Add Block Patterns

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsb/reveal-presentations#3]
I think in order to make it more obvious where content needs to be entered in the slide, we might consider adding a couple of block patterns, similar to what you see in PowerPoint. 

![image](https://user-images.githubusercontent.com/480667/132432587-fa9db61f-c793-48ef-a101-5f8de8172a82.png)

Just doing a bit more research first on the possibilities. No action required just yet.

**Comment by r-a-y** [comment]
I think we can definitely do something here.

If you can set up some example slides for each different pattern laid out, I can convert them into block patterns. I can also remove the existing WP core block patterns when on a slide post type admin page.

**Comment by mrjarbenne** [comment]
I've created three block patterns:

Heading and Paragraph
```
<!-- wp:slide/slide -->
<section class="wp-block-slide-slide"><!-- wp:heading {"level":1} -->
<h1></h1>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph --></section>
<!-- /wp:slide/slide -->
```

Heading and Text Columns 

```
<!-- wp:slide/slide -->
<section class="wp-block-slide-slide"><!-- wp:heading {"level":1} -->
<h1></h1>
<!-- /wp:heading -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></section>
<!-- /wp:slide/slide -->
```

Text and Media

```
<!-- wp:slide/slide -->
<section class="wp-block-slide-slide"><!-- wp:media-text {"mediaPosition":"right"} -->
<div class="wp-block-media-text alignwide has-media-on-the-right is-stacked-on-mobile"><figure class="wp-block-media-text__media"></figure><div class="wp-block-media-text__content"><!-- wp:paragraph {"placeholder":"Content…","fontSize":"large"} -->
<p class="has-large-font-size"></p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:media-text --></section>
<!-- /wp:slide/slide -->
```

**Comment by r-a-y** [comment]
I've got a first pass of this working:

![GIF of block patterns](https://user-images.githubusercontent.com/505921/133175558-f1a42a52-f1eb-483b-82db-c4edd72f5c14.gif)

For the Text and Media pattern, I needed to add an image otherwise the pattern wouldn't render. I chose to use the "C" used on the Commons site. Let me know if you want me to swap that image out for something else.

We also might want to wipe out all block patterns registered by other plugins or by the current theme. Some default Twenty* themes register some block patterns and they probably will not look good in a presentation.

**Comment by mrjarbenne** [comment]
Let's do this as the default image: 

<img width="500" alt="media-text-replace" src="https://user-images.githubusercontent.com/480667/133628124-ecdaa40e-7e3f-475d-a8a7-99b5d7fc7d03.png">

You are right about the block patterns. They will need to be wiped out if that's possible.

**Comment by r-a-y** [comment]
Can you upload that image to the Commons? Don't really want to rely on Github for the image.

**Comment by r-a-y** [comment]
> You are right about the block patterns. They will need to be wiped out if that's possible.

Just implemented this in commit 02e2dd3. A little hacky since I have to parse the current URL to determine which page we are on to remove the block patterns only on our post type pages.

**Comment by mrjarbenne** [comment]
> Can you upload that image to the Commons? Don't really want to rely on Github for the image.

https://hwdsbcommons.s3.amazonaws.com/wp-content/uploads/sites/65/2021/09/media-text-replace.png

**Comment by r-a-y** [comment]
> https://hwdsbcommons.s3.amazonaws.com/wp-content/uploads/sites/65/2021/09/media-text-replace.png

Done!
