### ISSUE TITLE
Remove Speaker Notes

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsb/reveal-presentations#4]
I've noticed a large number of users who are struggling to sort out where their content should go. I'm putting together the block patterns now (#3) but I think we need to eliminate the Speaker notes section from the interface as I've pulled a few announcements from there. 

Maybe we can comment out the speaker notes functionality for now, and then if the Presentations function begins to be utilized more widely than just for announcements, we can look at developing it out further with a toggle to enable the textbox or not on a presentation by presentation basis.

**Comment by r-a-y** [comment]
Perhaps we can move the Speaker Notes section into a metabox so it can be expanded or collapsed. It should be doable, but let me look into this.

**Comment by r-a-y** [comment]
Should be fixed in commit fdbc67f.

We can already add the speaker notes from the sidebar so we aren't losing any functionality from removing the main Speaker Notes section.
