### ISSUE TITLE
Inconsistency with Add Block + buttons

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsb/reveal-presentations#5]
When adding a new block, if you attempt to use the + button to the right of the content, it doesn't reveal the block selector screen but selects the slide context menu, but if you use the + button in the top of the editor, you get the expected behaviour: 

![2021-09-10_11-10-16 (1)](https://user-images.githubusercontent.com/480667/132876534-b9a6a5d8-cb7c-41b4-8adc-71b5e9defc43.gif)

Additionally when adding content like columns, in the post editor in the default theme, there are additional + prompts to indicate how to add content within the columns: 

<img width="937" alt="2021-09-10_11-02-16" src="https://user-images.githubusercontent.com/480667/132876871-13e73ce6-060c-4fbc-8198-c146d112356d.png">

but we don't see that on the slide post type block: 

![2021-09-10_11-10-16 copy (1)](https://user-images.githubusercontent.com/480667/132876902-5f5164f6-0410-4c34-9db9-b787092ae9a1.gif)

In the default post editor there seems to be more + buttons to ensure you are entering the content within the column, that might help with slide content entry. I'm assuming the + button from the first gif on the right is **outside** of the slide, and we need a + below the Heading block, still **within** the slide: 

<img width="1100" alt="2021-09-10_11-02-47" src="https://user-images.githubusercontent.com/480667/132877471-7c0b14d0-64c0-4c5d-8674-68a04f3829ed.png">

I wonder if this inconsistency is resulting in some of our erroneously placed content.

**Comment by mrjarbenne** [comment]
Note I added core/columns as an allowed type in order to construct one of the block patterns from #3

**Comment by r-a-y** [comment]
I think the original `slides` plugin deliberately hid some of the + buttons in an attempt to prevent people from adding unnecessary content above or below the slide. Will look into this.

**Comment by r-a-y** [comment]
Should be fixed in the commits above.

One main change I've made is to hide the post title from the admin area. This is to prevent accidental content from being added before the slide. I might need to re-save the post title on any post update with the slide's heading.
