### ISSUE TITLE
Slides Not UnPublishing

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsb/reveal-presentations#6]
It's being reported on a few different sites. I tested it here: 

https://announcementstemplate.commons.hwdsb.on.ca/presentation/announcements/#/slide-367

We are using the 2.0 version of Unpublish from Humanmade. I've checked that repo and there are no updates to pull in.

**Comment by r-a-y** [comment]
It's working for me. I just did a test with a user with the `contributor` role and with an adminstrator on the site. View the "Unpublish Test" posts in the trash of that site.

**Comment by mrjarbenne** [comment]
Hmmm. The link above is for a slide I scheduled to unpublish at 10:30 this morning. It's still live: 

![2021-09-22_17-06-38](https://user-images.githubusercontent.com/480667/134422121-0df3e556-4a4b-4d56-9ab9-0f0072a6afe6.png)

**Comment by r-a-y** [comment]
I'm not sure what went wrong with that slide. I can see in the server access logs that a cronjob ran at 10:46:54 am on that site.

The slide should have unpublished then. It's possible that the unpublish cronjob was not scheduled, but I'm not sure what would cause that. According to the Unpublish codebase, if the unpublish timestamp is blank, then a cronjob will not be scheduled: https://github.com/humanmade/Unpublish/blob/21a3126fc8d468ffefbdf204a102ed956dc9fb16/inc/post-meta.php#L53-L57

How often has this been occurring? If it is happening a lot, I can add some debug logs to see what could be causing this.

**Comment by mrjarbenne** [comment]
It was brought to my attention on this site (I've since cleaned it up) https://552.commons.hwdsb.on.ca

I'll spot check some others. I see my most recent post unpublished.

**Comment by r-a-y** [comment]
An easy way to see if the unpublish scheduled tasks are registered is to activate the WP Crontrol plugin and check for the `unpublish_post_cron` job. When a post is scheduled to be unpublished, check WP Crontrol to see if the job is registered at the timestamp.

I've just activated it on the 552 site: https://552.commons.hwdsb.on.ca/wp-admin/tools.php?page=crontrol_admin_manage_page
